### ISSUE TITLE
Text OCR location change

### ISSUE THREAD

**Issue by mguyard** [MichielvanBeers/notion-auto-ocr#1]
Hello,

Firstly thank for your work.
Do you have study the possibility to use image caption as paragraph replacement ?
Using caption, i think we will be able to use a block replacement and don't separate image and text (as for now, text is add in the bottom of page).

Do you have also study the usage of a property to set a page as a OCR ready to don't have to use Created time ? as Created time is set when page is create, if you work on a page during multiple hours or days, only images during the time between creation and scan frequency are parsed and after that, page is excluded from scan.
Using a property checkbox will be interresting way. You check the property when you have finish page edition and based on this, script will parsed images tagged with ocr_text

Before working of this type of change, do you already try it and are you interrested for a PR in this way (replacing text addition and search based on a image caption / place a mandatory checkbox in database to tag a page to be parsed) ?

**Comment by MichielvanBeers** [comment]
Hi Mguyard,

Thanks for your interest in this project! All of these sound like great suggestions for which I would happily receive a PR. My current personal use case is that I use it for an 'inbox' kind of setup, where I dump some snippets that I come across in my day-to-day and want to be able to search these.

I do like to have the ability to keep the images as well since the OCR isn't always perfect, so shall we make that a setting that can be set in Docker?

I'm happy to help with testing when you have a PR ready. Thanks in advance!

**Comment by mguyard** [comment]
PR is push. I've done some test with success.

> I do like to have the ability to keep the images as well since the OCR isn't always perfect, so shall we make that a setting that can be set in Docker?

I don't remove image. I only use caption. And for the search, i've add a DOCKER env option.
Documentation is updated and i've add a gif in doc to better explain what the change do : https://camo.githubusercontent.com/a70a9eb8f4ff410d897b117855397c58b047820e2237a6e82115f2167873311c/68747470733a2f2f692e696d6775722e636f6d2f6a6c3377314a692e676966

If 'ocr_text' is find in caption and in parapgrah after image, only caption is changed and a message explain in console.

**Comment by MichielvanBeers** [comment]
Pulled the new image, tested both single run and with scan_frequency parameter. Everything seems to be working 🎉! Closing this issue

**Comment by mguyard** [comment]
Perfect 👍
